[build]
  command = "npm run build:netlify"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/admin/sync-results-dry-run"
  to = "/.netlify/functions/sync-results-dry-run"
  status = 200

[[redirects]]
  from = "/api/admin/sync-results"
  to = "/.netlify/functions/sync-results"
  status = 200

[[redirects]]
  from = "/api/admin/sync-fixtures-dry-run"
  to = "/.netlify/functions/sync-fixtures-dry-run"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
